// this code is autogenerated, do not check it into to your code repository

// ref lib/aiex/tui/libvaxis_nif_minimal.ex:15
const beam = @import("beam");

/// Test basic Zig integration
pub fn zig_test() beam.term {
    return beam.make(.{.ok, .hello_from_zig}, .{});
}
