apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiex.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    {{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.prometheus.port }}
      targetPort: {{ .Values.monitoring.prometheus.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "aiex.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiex.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiex.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
    - name: epmd
      port: 4369
      targetPort: 4369
      protocol: TCP
    - name: cluster-min
      port: 9100
      targetPort: 9100
      protocol: TCP
    - name: cluster-max
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    {{- include "aiex.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true