apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aiex-pdb
  namespace: aiex
  labels:
    app.kubernetes.io/name: aiex
    app.kubernetes.io/instance: aiex
    app.kubernetes.io/component: disruption-budget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aiex
      app.kubernetes.io/instance: aiex