apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiex-data
  namespace: aiex
  labels:
    app.kubernetes.io/name: aiex
    app.kubernetes.io/instance: aiex
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple pods to access the same volume
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd  # Adjust based on your cluster's storage classes
---
# Alternative: StatefulSet storage for individual pod data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiex-logs
  namespace: aiex
  labels:
    app.kubernetes.io/name: aiex
    app.kubernetes.io/instance: aiex
    app.kubernetes.io/component: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard