apiVersion: v1
kind: Secret
metadata:
  name: aiex-secrets
  namespace: aiex
  labels:
    app.kubernetes.io/name: aiex
    app.kubernetes.io/instance: aiex
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets - these should be set during deployment
  # OpenAI API Key (base64 encoded)
  OPENAI_API_KEY: ""
  
  # Anthropic API Key (base64 encoded)
  ANTHROPIC_API_KEY: ""
  
  # Database credentials (if using external database)
  DB_USERNAME: ""
  DB_PASSWORD: ""
  
  # TLS certificates (if needed)
  TLS_CERT: ""
  TLS_KEY: ""
  
  # JWT signing key
  JWT_SECRET: ""
  
  # Encryption key for sensitive data
  ENCRYPTION_KEY: ""
---
# Example of how to create secrets:
# kubectl create secret generic aiex-secrets \
#   --from-literal=OPENAI_API_KEY="your-openai-key" \
#   --from-literal=ANTHROPIC_API_KEY="your-anthropic-key" \
#   --namespace=aiex